user_dir: "/home/vagrant"
app_port: 5000
service:
  workingdir: /home/vagrant/djangoapp/djangoapp
  execstart: /home/vagrant/djangoapp/env/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 djangoapp.wsgi:application

djangoservice:
  workingdir: /home/vagrant/djangoapp/djangoapp
  execstart: /home/vagrant/djangoapp/env/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 djangoapp.wsgi:application



app:
  env:
    SQLALCHEMY_DATABASE_URI: postgresql://dbuser:pass123@db01/db
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: sfvgbrh212131

django:
  env:
    SECRET_KEY: 'sfvgbrh212131'
    DATABASE_URL: 'postgresql://dbuser:pass123@db01/db'
