user_dir: "/home/azureuser"


djangoservice:
  workingdir: /home/azureuser/djangoapp/djangoapp
  execstart: /home/azureuser/djangoapp/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 djangoapp.wsgi:application

django:
  env:
    SECRET_KEY: 'sfvgbrh212131'
    DATABASE_URL: 'postgresql://dbuser:pass123@localhost/db'

user_name: azureuser
app_port: 8000
